


# target rules
# -----------------------------------------------------
rule all:
    default_target: True
    input:
        "results/c.txt",


rule A:
    output:
        a="results/a.txt",
    shell:
        "touch {output[0]}"


use rule A as B with:
    output:
        b="results/b.txt"


rule C:
    input:
        a="results/a.txt",
        b="results/b.txt",
    output:
        c="results/c.txt",
    shell:
        "cat {input.a} {input.b} > {output.c}"
